<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MPM.Modules.Alertas.Tests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MPM.Shared\MPM.Shared.csproj" />
    <ProjectReference Include="..\MPM.Core\MPM.Core.csproj" />
    <ProjectReference Include="..\MPM.Modules.Notificaciones\MPM.Modules.Notificaciones.csproj" />
    <ProjectReference Include="..\MPM.Modules.Analisis\MPM.Modules.Analisis.csproj" />
  </ItemGroup>

</Project>
